### ISSUE TITLE
Sumo can't squash all our domains into one, we should talk

### ISSUE THREAD

**Issue by mythmon** [mozilla/puente#16] opened 2015-10-27 19:44 UTC
> If you have a bunch of domains and can't squash them into `django.po(t)`
> and `javascript.po(t)`, then we should talk--open up an issue.

Sumo has several tools that extract strings. For example, there are tools in BuddyUp that generate a .pot file directly. We then use the tower merge command to merge those into the .po files. Tower's extract command doesn't do anything.

Options I can see:
1. Make puente support multiple domains, like tower did, despite making it further away from Django-core.
2. Modify BuddyUp to do something like the DB strings trick. It would generate a file that puente already knows how to extract from and put it somewhere puente will notice.
3. Write a extract tool that is compatible with puente that can extract from BuddyUp code, use puente's extract command, and ignore the one written for BuddyUp.
4. Ignore BuddyUp and never speak of this again.

**Comment by willkg** [comment] 2015-10-27 20:26
I chatted with @mythmon about this on IRC. The problem is that buddyup strings currently use `./manage.py merge` to get merged into the locale `.po` files.

I'm pretty sure I can replace that bit with a tiny shell script. I created a bug for that:

https://bugzilla.mozilla.org/show_bug.cgi?id=1218973

**Comment by willkg** [comment] 2015-10-27 20:27
Incidentally, I looked at other projects: MDN, AMO, Marketplace, Mozillians, SUMO and Input. SUMO is the only one that's got non messages/javascript files. So seems like if we can solve SUMO's problem with a shell script, we're good to go again plus we can rip out a bunch more code.

**Comment by willkg** [comment] 2015-10-28 17:09
We landed a shell script for SUMO and buddyup files. So we're all set here.

**Closed as completed by willkg** 2015-10-28 17:09 UTC
